<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
<?php
// iterate through the pages
foreach ($this->pages as $key => $page):
?>
<?php
// if this isn't the last page, add a link and the separator:
if ($key < count($this->pages) - 1):
?>
        <li class="breadcrumb-item">
            <a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
<?php
// otherwise, output the name only:
else:
?>
        <li class="breadcrumb-item active" aria-current="page">
            <?= $page->getLabel() ?>
<?php endif; ?>
        </li>
<?php endforeach; ?>
    </ol>
</nav>    